#
# Default users' accounts
#

- login:    demo
  password: demo
  email:    nohow@nowhere.com

# here you may define your admin's account, like that:
- login:   admin
  password: greencheese
  email: kaineer@gmail.com
  admin: true
